---
title: "Novel vs. repeated choice project: Fixations"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: 'hide'
---

# Set up environment and load in data

```{r include=FALSE}
library(tidyverse)
library(here)
theme_set(theme_bw())
helpers_path = paste0(here(),'/analysis/helpers/')
# source(paste0(helpers_path, '01_clean_behavioral_data.R'))
fig_out_path = paste0(here(), '/outputs/fig/')
```

# Eye-tracking 

```{r}
data_bc_fix = read.csv(paste0(here(), '/inputs/data_fixBC.csv'))

data_bc_fix = data_bc_fix %>%
  mutate(correct = ifelse(possiblePayoffleft>possiblePayoffright & leftChosen == 1, 1, ifelse(possiblePayoffleft<possiblePayoffright & leftChosen == 0, 1, 0))) %>%
  mutate(type = ifelse(typeLeft == 1, "HT", "RE")) %>%
  mutate(val_diff = possiblePayoffleft - possiblePayoffright,
         val_diff_bin = round(val_diff/50),
         val_diff_bin_str = ifelse(val_diff_bin == 0, "-50:50", 
                                   ifelse(val_diff_bin == 1, "50:100",
                                          ifelse(val_diff_bin == -1, "-100:-50",
                                                 ifelse(val_diff_bin == 2, "100:150",
                                                        ifelse(val_diff_bin == -2, "-150:-100",
                                                               ifelse(val_diff_bin == 3, "150:200",
                                                                      ifelse(val_diff_bin == -3, "-200:-150",
                                                                             ifelse(val_diff_bin == 4, "200:250", 
                                                                                    ifelse(val_diff_bin == -4, "-250:-200", 
                                                                                           ifelse(val_diff_bin == 5, "250:300",
                                                                                                  ifelse(val_diff_bin == -5, "-300:-250", NA))))))))))),
         val_diff_bin_str = factor(val_diff_bin_str, levels = c("-300:-250", "-250:-200", "-200:-150", "-150:-100", "-100:-50", "-50:50", "50:100", "100:150", "150:200", "200:250", "250:300")),
         abs_val_diff_bin_str = ifelse(val_diff_bin == 0, "0:50", 
                                       ifelse(abs(val_diff_bin) == 1, "50:100", 
                                              ifelse(abs(val_diff_bin) == 2, "100:150",
                                                     ifelse(abs(val_diff_bin) == 3, "150:200",
                                                            ifelse(abs(val_diff_bin) == 4, "200:250", 
                                                                   ifelse(abs(val_diff_bin) == 5, "250:300", NA)))))),
         abs_val_diff_bin_str = factor(abs_val_diff_bin_str, levels = c("0:50", "50:100", "100:150", "150:200", "200:250", "250:300")))
```

## p(Choice left)

```{r}
p = data_bc_fix %>%
  filter(!is.na(val_diff_bin_str)) %>%
  filter(lastFix == 1) %>%
  group_by(subnum, day, val_diff_bin_str, leftFix) %>%
  summarise(.groups = 'keep',
            mean_left_choice = mean(leftChosen),
            sem_left_choice = sd(leftChosen)/sqrt(n())) %>%
  mutate(lastFixLeft = ifelse(leftFix == 1, "Left", "Right"),
         day = paste0("Day ", day),
         day = factor(day, levels = c("Day 3", "Day 7", "Day 11"))) %>%
  ggplot(aes(val_diff_bin_str, mean_left_choice, color = lastFixLeft))+
  geom_point()+
  geom_errorbar(aes(ymin = mean_left_choice - sem_left_choice, ymax = mean_left_choice + sem_left_choice), width = 0)+
  geom_line(aes(group = lastFixLeft))+
  labs(title = "BC Task", x = "Value Left - Value Right", y = "p(Left Choice)", color="Last Fixation")+
  geom_hline(aes(yintercept=.5), color="gray", linetype = "longdash")+
  geom_vline(aes(xintercept=6), color="gray", linetype = "longdash")+
  facet_grid(subnum ~ day)+
  theme(panel.grid = element_blank(),
        legend.position = "bottom",
        axis.text.x = element_text(angle = 15, margin = margin(t = 5)),
        legend.box.margin=margin(t = -10))+
  scale_color_brewer(palette = "Set1")+
  scale_x_discrete(labels=c("", "-250:-200", "", "-150:-100", "", "-50:50", "", "100:150", "", "200:250", ""))+
  scale_y_continuous(breaks = seq(0,1,.5))

ggsave(file=paste0(fig_out_path, 'bc_pLeftOverValDiffByLastFix.jpg'), p, height = 5, width=8, units="in")
p
```

```{r}
p = data_bc_fix %>%
  filter(!is.na(val_diff_bin_str)) %>%
  filter(lastFix == 1) %>%
  group_by(subnum, day, val_diff_bin_str, leftFix) %>%
  summarise(.groups = 'keep',
            mean_left_choice = mean(leftChosen)) %>%
  ungroup() %>%
  mutate(lastFixLeft = ifelse(leftFix == 1, "Left", "Right")) %>%
  select(-leftFix) %>%
  group_by(day, val_diff_bin_str, lastFixLeft) %>%
  summarise(.groups = 'keep',
            sem_left_choice = sd(mean_left_choice)/sqrt(n()),
            mean_left_choice = mean(mean_left_choice)) %>%
  mutate(day = paste0("Day ", day),
         day = factor(day, levels = c("Day 3", "Day 7", "Day 11")),
         sem_left_choice = ifelse(is.na(sem_left_choice), 0, sem_left_choice)) %>%
    ggplot(aes(val_diff_bin_str, mean_left_choice, color = lastFixLeft))+
  geom_point()+
  geom_errorbar(aes(ymin = mean_left_choice - sem_left_choice, ymax = mean_left_choice + sem_left_choice), width = 0)+
  geom_line(aes(group = lastFixLeft))+
  labs(title = "BC Task", x = "Value Left - Value Right", y = "p(Left Choice)", color="Last Fixation")+
  geom_hline(aes(yintercept=.5), color="gray", linetype = "longdash")+
  geom_vline(aes(xintercept=6), color="gray", linetype = "longdash")+
  facet_grid(. ~ day)+
  theme(panel.grid = element_blank(),
        legend.position = "bottom",
        axis.text.x = element_text(angle = 15, margin = margin(t = 5)),
        legend.box.margin=margin(t = -10))+
  scale_color_brewer(palette = "Set1")+
  scale_x_discrete(labels=c("", "-250:-200", "", "-150:-100", "", "-50:50", "", "100:150", "", "200:250", ""))+
  scale_y_continuous(breaks = seq(0,1,.5))

ggsave(file=paste0(fig_out_path, 'bc_group_pLeftOverValDiffByLastFix.jpg'), p, height = 3, width=9, units="in")
p
```

```{r}
p = data_bc_fix %>%
  filter(!is.na(val_diff_bin_str)) %>%
  filter(lastFix == 1) %>%
  filter(type == "HT") %>%
  group_by(subnum, day, val_diff_bin_str, leftFix) %>%
  summarise(.groups = 'keep',
            mean_left_choice = mean(leftChosen),
            sem_left_choice = sd(leftChosen)/sqrt(n())) %>%
  mutate(lastFixLeft = ifelse(leftFix == 1, "Left", "Right"),
         day = paste0("Day ", day),
         day = factor(day, levels = c("Day 3", "Day 7", "Day 11"))) %>%
  ggplot(aes(val_diff_bin_str, mean_left_choice, color = lastFixLeft))+
  geom_point()+
  geom_errorbar(aes(ymin = mean_left_choice - sem_left_choice, ymax = mean_left_choice + sem_left_choice), width = 0)+
  geom_line(aes(group = lastFixLeft))+
  labs(title = "BC Task - HT stimuli", x = "Value Left - Value Right", y = "p(Left Choice)", color="Last Fixation")+
  geom_hline(aes(yintercept=.5), color="gray", linetype = "longdash")+
  geom_vline(aes(xintercept=6), color="gray", linetype = "longdash")+
  facet_grid(subnum ~ day)+
  theme(panel.grid = element_blank(),
        legend.position = "bottom",
        axis.text.x = element_text(angle = 15, margin = margin(t = 5)),
        legend.box.margin=margin(t = -10))+
  scale_color_brewer(palette = "Set1")+
  scale_x_discrete(labels=c("", "-250:-200", "", "-150:-100", "", "-50:50", "", "100:150", "", "200:250", ""))+
  scale_y_continuous(breaks = seq(0,1,.5))

ggsave(file=paste0(fig_out_path, 'bc_pLeftOverValDiffByLastFixHTStim.jpg'), p, height = 5, width=8, units="in")
p
```

```{r}
p = data_bc_fix %>%
  filter(!is.na(val_diff_bin_str)) %>%
  filter(lastFix == 1) %>%
  filter(type == "RE") %>%
  group_by(subnum, day, val_diff_bin_str, leftFix) %>%
  summarise(.groups = 'keep',
            mean_left_choice = mean(leftChosen),
            sem_left_choice = sd(leftChosen)/sqrt(n())) %>%
  mutate(lastFixLeft = ifelse(leftFix == 1, "Left", "Right"),
         day = paste0("Day ", day),
         day = factor(day, levels = c("Day 3", "Day 7", "Day 11"))) %>%
  ggplot(aes(val_diff_bin_str, mean_left_choice, color = lastFixLeft))+
  geom_point()+
  geom_errorbar(aes(ymin = mean_left_choice - sem_left_choice, ymax = mean_left_choice + sem_left_choice), width = 0)+
  geom_line(aes(group = lastFixLeft))+
  labs(title = "BC Task - RE stimuli", x = "Value Left - Value Right", y = "p(Left Choice)", color="Last Fixation")+
  geom_hline(aes(yintercept=.5), color="gray", linetype = "longdash")+
  geom_vline(aes(xintercept=6), color="gray", linetype = "longdash")+
  facet_grid(subnum ~ day)+
  theme(panel.grid = element_blank(),
        legend.position = "bottom",
        axis.text.x = element_text(angle = 15, margin = margin(t = 5)),
        legend.box.margin=margin(t = -10))+
  scale_color_brewer(palette = "Set1")+
  scale_x_discrete(labels=c("", "-250:-200", "", "-150:-100", "", "-50:50", "", "100:150", "", "200:250", ""))+
  scale_y_continuous(breaks = seq(0,1,.5))

ggsave(file=paste0(fig_out_path, 'bc_pLeftOverValDiffByLastFixREStim.jpg'), p, height = 5, width=8, units="in")
p
```

```{r}
p = data_bc_fix %>%
  filter(!is.na(val_diff_bin_str)) %>%
  filter(lastFix == 1) %>%
  group_by(subnum, day, val_diff_bin_str, leftFix, type) %>%
  summarise(.groups = 'keep',
            mean_left_choice = mean(leftChosen)) %>%
  ungroup() %>%
  mutate(lastFixLeft = ifelse(leftFix == 1, "Left", "Right")) %>%
  select(-leftFix) %>%
  group_by(day, val_diff_bin_str, lastFixLeft, type) %>%
  summarise(.groups = 'keep',
            sem_left_choice = sd(mean_left_choice)/sqrt(n()),
            mean_left_choice = mean(mean_left_choice)) %>%
  mutate(day = paste0("Day ", day),
         day = factor(day, levels = c("Day 3", "Day 7", "Day 11")),
         sem_left_choice = ifelse(is.na(sem_left_choice), 0, sem_left_choice)) %>%
    ggplot(aes(val_diff_bin_str, mean_left_choice, color = lastFixLeft))+
  geom_point()+
  geom_errorbar(aes(ymin = mean_left_choice - sem_left_choice, ymax = mean_left_choice + sem_left_choice), width = 0)+
  geom_line(aes(group = lastFixLeft))+
  labs(title = "BC Task", x = "Value Left - Value Right", y = "p(Left Choice)", color="Last Fixation")+
  geom_hline(aes(yintercept=.5), color="gray", linetype = "longdash")+
  geom_vline(aes(xintercept=6), color="gray", linetype = "longdash")+
  facet_grid(type ~ day)+
  theme(panel.grid = element_blank(),
        legend.position = "bottom",
        axis.text.x = element_text(angle = 15, margin = margin(t = 5)),
        legend.box.margin=margin(t = -10))+
  scale_color_brewer(palette = "Set1")+
  scale_x_discrete(labels=c("", "-250:-200", "", "-150:-100", "", "-50:50", "", "100:150", "", "200:250", ""))+
  scale_y_continuous(breaks = seq(0,1,.5))

ggsave(file=paste0(fig_out_path, 'bc_group_pLeftOverValDiffByLastFixByStim.jpg'), p, height = 5, width=9, units="in")
p
```

Logit fit

```{r}
lme4::glmer()
```

```{r}
p = data_bc_fix %>%
  filter(abs(val_diff_bin) < 6) %>%
  group_by(subnum, day, type, trialNum, leftFix) %>%
  summarise(.groups = "keep",
            totalFixDuration = sum(fixDuration), 
            leftChosen = unique(leftChosen)) %>%
  mutate(leftFix = ifelse(leftFix == 1, "leftDur", "rightDur")) %>%
  spread(leftFix, totalFixDuration) %>%
  select(-rightDur) %>%
  filter(!is.na(leftDur)) %>%
  mutate(logLeftDur = log(leftDur),
         logLeftDurBin = round(logLeftDur)) %>%
  ungroup() %>%
  group_by(subnum, day, type, logLeftDurBin) %>%
  summarise(.groups = 'keep',
            mean_left_choice = mean(leftChosen)) %>%
  ungroup() %>%
  group_by(day, type, logLeftDurBin) %>%
  summarise(.groups = 'keep',
            sem_left_choice = sd(mean_left_choice)/sqrt(n()),
            mean_left_choice = mean(mean_left_choice)) %>%
  mutate(day = paste0("Day ", day),
         day = factor(day, levels = c("Day 3", "Day 7", "Day 11")),
         expLogLeftDurBin = round(exp(logLeftDurBin))) %>%
  ggplot(aes(as.factor(expLogLeftDurBin), mean_left_choice, color = type))+
  geom_point()+
  geom_errorbar(aes(ymin = mean_left_choice - sem_left_choice, ymax = mean_left_choice + sem_left_choice), width = 0)+
  geom_line(aes(group = type))+
  labs(title = "BC Task", y = "p(Left Choice)", x = "Left Fixation Duration", color="")+
  geom_hline(aes(yintercept=.5), color="gray", linetype = "longdash")+
  facet_grid(. ~ day)+
  theme(panel.grid = element_blank(),
        legend.position = "bottom",
        axis.text.x = element_text(margin = margin(t = 5)),
        legend.box.margin=margin(t = -10))+
  scale_color_brewer(palette = "Dark2")

ggsave(file=paste0(fig_out_path, 'bc_group_pLeftOverNetFixLeftByStim.jpg'), p, height = 3, width=9, units="in")
p
```

```{r}
p = data_bc_fix %>%
  filter(abs(val_diff_bin) < 6) %>%
  group_by(subnum, day, type, trialNum, leftFix) %>%
  summarise(.groups = "keep",
            totalFixDuration = sum(fixDuration), 
            leftChosen = unique(leftChosen)) %>%
  mutate(leftFix = ifelse(leftFix == 1, "leftDur", "rightDur")) %>%
  spread(leftFix, totalFixDuration) %>%
  select(-rightDur) %>%
  filter(!is.na(leftDur)) %>%
  mutate(logLeftDur = log(leftDur),
         logLeftDurBin = round(logLeftDur)) %>%
  ungroup() %>%
  group_by(subnum, day, type, logLeftDurBin) %>%
  summarise(.groups = 'keep',
            sem_left_choice = sd(leftChosen)/sqrt(n()),
            mean_left_choice = mean(leftChosen)) %>%
  mutate(day = paste0("Day ", day),
         day = factor(day, levels = c("Day 3", "Day 7", "Day 11")),
         expLogLeftDurBin = round(exp(logLeftDurBin))) %>%
  ggplot(aes(as.factor(expLogLeftDurBin), mean_left_choice, color = type))+
  geom_point()+
  geom_errorbar(aes(ymin = mean_left_choice - sem_left_choice, ymax = mean_left_choice + sem_left_choice), width = 0)+
  geom_line(aes(group = type))+
  labs(title = "BC Task", y = "p(Left Choice)", x = "Left Fixation Duration", color="")+
  geom_hline(aes(yintercept=.5), color="gray", linetype = "longdash")+
  facet_grid(subnum ~ day)+
  theme(panel.grid = element_blank(),
        legend.position = "bottom",
        axis.text.x = element_text(margin = margin(t = 5)),
        legend.box.margin=margin(t = -10))+
  scale_color_brewer(palette = "Dark2")

ggsave(file=paste0(fig_out_path, 'bc_pLeftOverNetFixLeftByStim.jpg'), p, height = 5, width=8, units="in")
p
```

## p(Choice == First fixated)

```{r}
data_bc_fix %>%
  filter(firstFix == 1) %>%
  mutate(firstFixChosen = ifelse(leftFix == leftChosen, 1, 0))


# ggsave(file=paste0(fig_out_path, 'bc_pFirstFixatedOverFirstFixDurByStim.jpg'), p, height = 3, width=9, units="in")
# p
```

## p(First Fix == Left)

```{r}
p = data_bc_fix %>%
  filter(!is.na(val_diff_bin_str)) %>%
  filter(firstFix == 1) %>%
  group_by(subnum, day, type, val_diff_bin_str) %>%
  summarise(mean_first_fix_left = mean(leftFix), .groups="keep") %>%
  ungroup() %>%
  group_by(day, type, val_diff_bin_str) %>%
  summarise(.groups = 'keep',
            sem_first_fix_left = sd(mean_first_fix_left)/sqrt(n()),
            mean_first_fix_left = mean(mean_first_fix_left)) %>%
  mutate(day = paste0("Day ", day),
         day = factor(day, levels = c("Day 3", "Day 7", "Day 11"))) %>%
  ggplot(aes(val_diff_bin_str, mean_first_fix_left, color = type))+
  geom_point()+
  geom_errorbar(aes(ymin = mean_first_fix_left - sem_first_fix_left, ymax = mean_first_fix_left + sem_first_fix_left), width = 0)+
  geom_line(aes(group = type))+
  labs(title = "BC Task", x = "Value Left - Value Right", y = "p(First Fixation == Left)", color="")+
  geom_hline(aes(yintercept=.5), color="gray", linetype = "longdash")+
  geom_vline(aes(xintercept=6), color="gray", linetype = "longdash")+
  facet_grid(. ~ day)+
  theme(panel.grid = element_blank(),
        legend.position = "bottom",
        axis.text.x = element_text(angle = 15, margin = margin(t = 5)),
        legend.box.margin=margin(t = -10))+
  scale_color_brewer(palette = "Dark2")+
  scale_x_discrete(labels=c("", "-250:-200", "", "-150:-100", "", "-50:50", "", "100:150", "", "200:250", ""))+
  scale_y_continuous(breaks = seq(0,1,.5))

ggsave(file=paste0(fig_out_path, 'bc_group_pFirstFixLeftOverValDiff.jpg'), p, height = 3, width=9, units="in")
p
```

```{r}
p = data_bc_fix %>%
  filter(!is.na(val_diff_bin_str)) %>%
  filter(firstFix == 1) %>%
  group_by(subnum, day, type, val_diff_bin_str) %>%
  summarise(mean_first_fix_left = mean(leftFix),
            sem_first_fix_left = sd(leftFix)/sqrt(n()), .groups="keep") %>%
  mutate(day = paste0("Day ", day),
         day = factor(day, levels = c("Day 3", "Day 7", "Day 11"))) %>%
  ggplot(aes(val_diff_bin_str, mean_first_fix_left, color = type))+
  geom_point()+
  geom_errorbar(aes(ymin = mean_first_fix_left - sem_first_fix_left, ymax = mean_first_fix_left + sem_first_fix_left), width = 0)+
  geom_line(aes(group = type))+
  labs(title = "BC Task", x = "Value Left - Value Right", y = "p(First Fixation == Left)", color="")+
  geom_hline(aes(yintercept=.5), color="gray", linetype = "longdash")+
  geom_vline(aes(xintercept=6), color="gray", linetype = "longdash")+
  facet_grid(subnum ~ day)+
  theme(panel.grid = element_blank(),
        legend.position = "bottom",
        axis.text.x = element_text(angle = 15, margin = margin(t = 5)),
        legend.box.margin=margin(t = -10))+
  scale_color_brewer(palette = "Dark2")+
  scale_x_discrete(labels=c("", "-250:-200", "", "-150:-100", "", "-50:50", "", "100:150", "", "200:250", ""))+
  scale_y_continuous(breaks = seq(0,1,.5))

ggsave(file=paste0(fig_out_path, 'bc_pFirstFixLeftOverValDiff.jpg'), p, height = 5, width=8, units="in")
p
```

## p(First Fix == Best)

```{r}
p = data_bc_fix %>%
  filter(!is.na(val_diff_bin_str)) %>%
  filter(firstFix == 1) %>%
  mutate(firstFixToBest = ifelse(leftFix == 1 & val_diff > 0, 1, ifelse(leftFix == 0 & val_diff < 0, 1, 0))) %>%
  group_by(subnum, day, type, val_diff_bin_str) %>%
  summarise(mean_first_fix_best = mean(firstFixToBest), .groups="keep") %>%
  ungroup() %>%
  group_by(day, type, val_diff_bin_str) %>%
  summarise(.groups = 'keep',
            sem_first_fix_best = sd(mean_first_fix_best)/sqrt(n()),
            mean_first_fix_best = mean(mean_first_fix_best)) %>%
  mutate(day = paste0("Day ", day),
         day = factor(day, levels = c("Day 3", "Day 7", "Day 11")))%>%
  ggplot(aes(val_diff_bin_str, mean_first_fix_best, color = type))+
  geom_point()+
  geom_errorbar(aes(ymin = mean_first_fix_best - sem_first_fix_best, ymax = mean_first_fix_best + sem_first_fix_best), width = 0)+
  geom_line(aes(group = type))+
  labs(title = "BC Task", x = "Value Left - Value Right", y = "p(First Fixation == Better Option)", color="")+
  geom_hline(aes(yintercept=.5), color="gray", linetype = "longdash")+
  geom_vline(aes(xintercept=6), color="gray", linetype = "longdash")+
  facet_grid(.~ day)+
  theme(panel.grid = element_blank(),
        legend.position = "bottom",
        axis.text.x = element_text(angle = 15, margin = margin(t = 5)),
        legend.box.margin=margin(t = -10))+
  scale_color_brewer(palette = "Dark2")+
  scale_x_discrete(labels=c("", "-250:-200", "", "-150:-100", "", "-50:50", "", "100:150", "", "200:250", ""))+
  scale_y_continuous(breaks = seq(0,1,.5))

ggsave(file=paste0(fig_out_path, 'bc_group_pFirstFixBestOverValDiff.jpg'), p, height = 3, width=9, units="in")
p
```


```{r}
p = data_bc_fix %>%
  filter(!is.na(val_diff_bin_str)) %>%
  filter(firstFix == 1) %>%
  mutate(firstFixToBest = ifelse(leftFix == 1 & val_diff > 0, 1, ifelse(leftFix == 0 & val_diff < 0, 1, 0))) %>%
  group_by(subnum, day, type, val_diff_bin_str) %>%
  summarise(mean_first_fix_best = mean(firstFixToBest),
            sem_first_fix_best = sd(firstFixToBest)/sqrt(n()), .groups="keep") %>%
  mutate(day = paste0("Day ", day),
         day = factor(day, levels = c("Day 3", "Day 7", "Day 11")))%>%
  ggplot(aes(val_diff_bin_str, mean_first_fix_best, color = type))+
  geom_point()+
  geom_errorbar(aes(ymin = mean_first_fix_best - sem_first_fix_best, ymax = mean_first_fix_best + sem_first_fix_best), width = 0)+
  geom_line(aes(group = type))+
  labs(title = "BC Task", x = "Value Left - Value Right", y = "p(First Fixation == Better Option)", color="")+
  geom_hline(aes(yintercept=.5), color="gray", linetype = "longdash")+
  geom_vline(aes(xintercept=6), color="gray", linetype = "longdash")+
  facet_grid(subnum ~ day)+
  theme(panel.grid = element_blank(),
        legend.position = "bottom",
        axis.text.x = element_text(angle = 15, margin = margin(t = 5)),
        legend.box.margin=margin(t = -10))+
  scale_color_brewer(palette = "Dark2")+
  scale_x_discrete(labels=c("", "-250:-200", "", "-150:-100", "", "-50:50", "", "100:150", "", "200:250", ""))+
  scale_y_continuous(breaks = seq(0,1,.5))

ggsave(file=paste0(fig_out_path, 'bc_pFirstFixBestOverValDiff.jpg'), p, height = 5, width=8, units="in")
p
```

## Number of fixations

```{r}
p = data_bc_fix %>%
  filter(!is.na(val_diff_bin_str)) %>%
  filter(lastFix == 1) %>%
  group_by(subnum, day, type, val_diff_bin_str) %>%
  summarise(mean_num_fix = mean(numTotalFix), .groups="keep") %>%
  ungroup() %>%
  group_by(day, type, val_diff_bin_str) %>%
  summarise(.groups = 'keep',
            sem_num_fix = sd(mean_num_fix)/sqrt(n()),
            mean_num_fix = mean(mean_num_fix)) %>%
  mutate(day = paste0("Day ", day),
         day = factor(day, levels = c("Day 3", "Day 7", "Day 11")))%>%
  ggplot(aes(val_diff_bin_str, mean_num_fix, color = type))+
  geom_point()+
  geom_errorbar(aes(ymin = mean_num_fix - sem_num_fix, ymax = mean_num_fix + sem_num_fix), width = 0)+
  geom_line(aes(group = type))+
  labs(title = "BC Task", x = "Value Left - Value Right", y = "Mean Number of Fixations", color="")+
  geom_hline(aes(yintercept=.5), color="gray", linetype = "longdash")+
  geom_vline(aes(xintercept=6), color="gray", linetype = "longdash")+
  facet_grid(. ~ day)+
  theme(panel.grid = element_blank(),
        legend.position = "bottom",
        axis.text.x = element_text(angle = 15, margin = margin(t = 5)),
        legend.box.margin=margin(t = -10))+
  scale_color_brewer(palette = "Dark2")+
  scale_x_discrete(labels=c("", "-250:-200", "", "-150:-100", "", "-50:50", "", "100:150", "", "200:250", ""))

ggsave(file=paste0(fig_out_path, 'bc_group_meanNumFixOverValDiff.jpg'), p, height = 3, width=9, units="in")
p
```

```{r}
p = data_bc_fix %>%
  filter(!is.na(val_diff_bin_str)) %>%
  filter(lastFix == 1) %>%
  group_by(subnum, day, type, val_diff_bin_str) %>%
  summarise(mean_num_fix = mean(numTotalFix),
            sem_num_fix = sd(numTotalFix)/sqrt(n()), .groups="keep") %>%
  mutate(day = paste0("Day ", day),
         day = factor(day, levels = c("Day 3", "Day 7", "Day 11")))%>%
  ggplot(aes(val_diff_bin_str, mean_num_fix, color = type))+
  geom_point()+
  geom_errorbar(aes(ymin = mean_num_fix - sem_num_fix, ymax = mean_num_fix + sem_num_fix), width = 0)+
  geom_line(aes(group = type))+
  labs(title = "BC Task", x = "Value Left - Value Right", y = "Mean Number of Fixations", color="")+
  geom_hline(aes(yintercept=.5), color="gray", linetype = "longdash")+
  geom_vline(aes(xintercept=6), color="gray", linetype = "longdash")+
  facet_grid(subnum ~ day, scales = 'free_y')+
  theme(panel.grid = element_blank(),
        legend.position = "bottom",
        axis.text.x = element_text(angle = 15, margin = margin(t = 5)),
        legend.box.margin=margin(t = -10))+
  scale_color_brewer(palette = "Dark2")+
  scale_x_discrete(labels=c("", "-250:-200", "", "-150:-100", "", "-50:50", "", "100:150", "", "200:250", ""))

ggsave(file=paste0(fig_out_path, 'bc_meanNumFixOverValDiff.jpg'), p, height = 5, width=8, units="in")
p
```


```{r}
p = data_bc_fix %>%
  filter(!is.na(val_diff_bin_str)) %>%
  filter(lastFix == 1) %>%
  group_by(subnum, day, type) %>%
  summarise(mean_num_fix = mean(numTotalFix), .groups="keep") %>%
  ungroup() %>%
  group_by(day, type) %>%
  summarise(sem_num_fix = sd(mean_num_fix)/sqrt(n()),
            mean_num_fix = mean(mean_num_fix), .groups="keep") %>%
  ggplot(aes(day, mean_num_fix, color = type))+
  geom_point()+
  geom_errorbar(aes(ymin = mean_num_fix - sem_num_fix, ymax = mean_num_fix + sem_num_fix), width = 0)+
  geom_line(aes(group = type))+
  labs(title = "BC Task", x = "Day", y = "Mean Number of Fixations", color="")+
  theme(panel.grid = element_blank(),
        legend.position = "bottom",
        axis.text.x = element_text(angle = 15, margin = margin(t = 5)),
        legend.box.margin=margin(t = -10))+
  scale_color_brewer(palette = "Dark2")+
  scale_x_continuous(breaks = c(3, 7, 11))

ggsave(file=paste0(fig_out_path, 'bc_group_meanNumFixOverDays.jpg'), p, height = 5, width=8, units="in")
p
```

```{r}
p = data_bc_fix %>%
  filter(!is.na(val_diff_bin_str)) %>%
  filter(lastFix == 1) %>%
  group_by(subnum, day, type) %>%
  summarise(mean_num_fix = mean(numTotalFix),
            sem_num_fix = sd(numTotalFix)/sqrt(n()), .groups="keep") %>%
  ggplot(aes(day, mean_num_fix, color = type))+
  geom_point()+
  geom_errorbar(aes(ymin = mean_num_fix - sem_num_fix, ymax = mean_num_fix + sem_num_fix), width = 0)+
  geom_line(aes(group = type))+
  labs(title = "BC Task", x = "Day", y = "Mean Number of Fixations", color="")+
  facet_wrap(~subnum)+
  theme(panel.grid = element_blank(),
        legend.position = "bottom",
        axis.text.x = element_text(angle = 15, margin = margin(t = 5)),
        legend.box.margin=margin(t = -10))+
  scale_color_brewer(palette = "Dark2")+
  scale_x_continuous(breaks = c(3, 7, 11))

ggsave(file=paste0(fig_out_path, 'bc_meanNumFixOverDays.jpg'), p, height = 5, width=8, units="in")
p
```

y: relative fixation time
x: relative value difference
color: HT vs RE

```{r}
p = data_bc_fix %>%
  filter(abs(val_diff_bin) < 6) %>%
  group_by(subnum, day, type, trialNum, leftFix, val_diff_bin_str) %>%
  summarise(.groups = "keep",
            totalFixDuration = sum(fixDuration)) %>%
  mutate(leftFix = ifelse(leftFix == 1, "LeftDur", "RightDur")) %>%
  spread(leftFix, totalFixDuration) %>%
  mutate(LeftDur = ifelse(is.na(LeftDur), 0, LeftDur),
         RightDur = ifelse(is.na(RightDur), 0, RightDur),
         propLeftFixDur = LeftDur/ (RightDur+LeftDur)) %>%
  ungroup() %>%
  group_by(subnum, day, type, val_diff_bin_str) %>%
  summarise(.groups = "keep",
            mean_propLeftFixDur = mean(propLeftFixDur)) %>%
  ungroup() %>%
  group_by(day, type, val_diff_bin_str) %>%
  summarise(.groups = 'keep',
            sem_propLeftFixDur = sd(mean_propLeftFixDur)/sqrt(n()),
            mean_propLeftFixDur = mean(mean_propLeftFixDur)) %>%
  mutate(day = paste0("Day ", day),
         day = factor(day, levels = c("Day 3", "Day 7", "Day 11")))%>%
  ggplot(aes(val_diff_bin_str, mean_propLeftFixDur, color = type))+
  geom_point()+
  geom_errorbar(aes(ymin = mean_propLeftFixDur - sem_propLeftFixDur, ymax = mean_propLeftFixDur + sem_propLeftFixDur), width = 0)+
  geom_line(aes(group = type))+
  labs(title = "BC Task", x = "Value Left - Value Right", y = "Proportion of Left Fixation Duration", color="")+
  geom_hline(aes(yintercept=.5), color="gray", linetype = "longdash")+
  geom_vline(aes(xintercept=6), color="gray", linetype = "longdash")+
  facet_grid(. ~ day)+
  theme(panel.grid = element_blank(),
        legend.position = "bottom",
        axis.text.x = element_text(angle = 15, margin = margin(t = 5)),
        legend.box.margin=margin(t = -10))+
  scale_color_brewer(palette = "Dark2")+
  scale_x_discrete(labels=c("", "-250:-200", "", "-150:-100", "", "-50:50", "", "100:150", "", "200:250", ""))

ggsave(file=paste0(fig_out_path, 'bc_group_propLeftFixDurOverValDiff.jpg'), p, height = 3, width=9, units="in")
p
```

```{r}
p = data_bc_fix %>%
  filter(!is.na(val_diff_bin_str)) %>%
  group_by(subnum, day, type, trialNum, leftFix, val_diff_bin_str) %>%
  summarise(.groups = "keep",
            totalFixDuration = sum(fixDuration)) %>%
  mutate(leftFix = ifelse(leftFix == 1, "LeftDur", "RightDur")) %>%
  spread(leftFix, totalFixDuration) %>%
  mutate(LeftDur = ifelse(is.na(LeftDur), 0, LeftDur),
         RightDur = ifelse(is.na(RightDur), 0, RightDur),
         propLeftFixDur = LeftDur/ (RightDur+LeftDur)) %>%
  ungroup() %>%
  group_by(subnum, day, type, val_diff_bin_str) %>%
  summarise(.groups = "keep",
            mean_propLeftFixDur = mean(propLeftFixDur),
            sem_propLeftFixDur = sd(propLeftFixDur)/sqrt(n())) %>%
  mutate(day = paste0("Day ", day),
         day = factor(day, levels = c("Day 3", "Day 7", "Day 11")))%>%
  ggplot(aes(val_diff_bin_str, mean_propLeftFixDur, color = type))+
  geom_point()+
  geom_errorbar(aes(ymin = mean_propLeftFixDur - sem_propLeftFixDur, ymax = mean_propLeftFixDur + sem_propLeftFixDur), width = 0)+
  geom_line(aes(group = type))+
  labs(title = "BC Task", x = "Value Left - Value Right", y = "Proportion of Left Fixation Duration", color="")+
  geom_hline(aes(yintercept=.5), color="gray", linetype = "longdash")+
  geom_vline(aes(xintercept=6), color="gray", linetype = "longdash")+
  facet_grid(subnum ~ day, scales = 'free_y')+
  theme(panel.grid = element_blank(),
        legend.position = "bottom",
        axis.text.x = element_text(angle = 15, margin = margin(t = 5)),
        legend.box.margin=margin(t = -10))+
  scale_color_brewer(palette = "Dark2")+
  scale_x_discrete(labels=c("", "-250:-200", "", "-150:-100", "", "-50:50", "", "100:150", "", "200:250", ""))

ggsave(file=paste0(fig_out_path, 'bc_propLeftFixDurOverValDiff.jpg'), p, height = 5, width=8, units="in")
p
```
