options:
  mri_ext: PAR
  debug: False
  n_cores: 4
  subject_stem: sub
  deface: False
  spinoza_data: False
  out_dir: overtrained_decisions_fmri

mappings:
  bold: _fmri
  T1w: _t1w3danat
  events: log
  physio: [1-9].log

func:
  yn-task1:
    id: run1
    task: yes-no
    run: 1
  yn-task2:
    id: run2
    task: yes-no
    run: 2
  bc-task:
    id: run3
    task: binary-choice
    run: 3
